### ISSUE TITLE
训练时出错

### ISSUE THREAD

**Issue by geek12138** [tomchen-ctj/OST#3]
训练时在 OST.py 的224行发生错误，显示在 model.py 的203行IndexError: tuple index out of range。
应该是连续两次self.text_encoder导致的，请问该如何解决？

**Comment by tomchen-ctj** [comment]
Hi, thanks for your attention!
Could you please provide more detail, e.g. the shape of the 'local_temporal_token' in your experimental setting?

**Comment by geek12138** [comment]
使用的是实验的默认设置，没有更改过其它地方，跑零样本测试时正常，且能得到和论文中几乎一致的结果。就是训练时出了这个问题。

**Comment by tomchen-ctj** [comment]
Hi,
I just built a new environment and I did not meet the problem you have encountered. (I'm trying few-shot fine-tuning, but it should be the same with respect to zero-shot training) Please try to build the environment according to the requirements again!
<img width="1165" alt="image" src="https://github.com/user-attachments/assets/5719e9ab-f4fb-4ae1-af50-a34c6d693191">

**Comment by tomchen-ctj** [comment]
Hi, I‘m closing the issue, if you have further questions, feel free to reopen the issue!
