### ISSUE TITLE
About few-shot task finetuned K400

### ISSUE THREAD

**Issue by yiyuyuyi** [tomchen-ctj/OST#4]
Hello, thank you for the inspiring open-source work!

I was wondering how to reproduce the few-shot task fine-tuned on K-400. Could you please provide information on how the CLIP model fine-tuned on K400 was trained? Is it possible to share the hyperparameters used during training? Thanks a lot!

**Comment by tomchen-ctj** [comment]
Hi @yiyuyuyi, 
Thanks for your attention!

In the K-400 fine-tuned few-shot setting, we simply replaced the original CLIP model with our best model in the zero-shot setting. For the training process and hyperparameters, you can simply refer to the zero-shot training setting with the following command:

`python -m torch.distributed.launch --nproc_per_node=8 main_nce.py -cfg configs/zero_shot/train/k400/16_32_ost.yaml --output /PATH/TO/OUTPUT `

The config file corresponding to this setting can be found [here](https://github.com/tomchen-ctj/OST/blob/main/configs/zero_shot/train/k400/16_32_ost.yaml).

If you have any further questions, please let me know.
